var candidates=[];var nStart,nStop;$.getJSON("js/questions.json",function(data){for(var i=0;i<data.candidates.length;i++){candidates.push(data.candidates[i]);};var t=0;do{var total=[0,0,0];var max=0;var questions=[];for(var i=0;i<9;i++){var list=data.questions[i].question.slice(0);var q=list.shuffle()[0];total.add(q.score1).add(q.score2);questions.push(q);};t++;}while(Math.abs(total[0]- total[1])>1||Math.abs(total[0]- total[2])>1);for(var i=0;i<questions.length;i++){var view=data.questions[i].view;var viewId=data.questions[i].vid;var slidesCtrl=(i==questions.length-1)?" last-question":" slidesjs-next slidesjs-navigation";var back=(i==0)?"":"<a href='#' class='back slidesjs-previous slidesjs-navigation'>上一題</a>";var skip=(i==questions.length-1)?" last-question":" slidesjs-next slidesjs-navigation";$("#view-selection").append("<div class='view'><div class='view-inside'><img src='img/i-"+(i+1)+".png'></div><h3>"+ view);$("#view-overlay").append("<div class='view' id='v-"+viewId+"'>");$("#progress-bar").append("<div class='bar "+((i==0)?"current":"")+"'>");$("<div id='view-"+ i+"' class='question'>").append("<div class='view-icon'><img src='img/i-"+(i+1)+".png'/>").append("<h2 class='view-title'>"+ view).append("<div class='q-title'><p>"+ questions[i].q).appendTo("#questions");$("<div class='options'>").append($("<div class='option"+slidesCtrl+"'>").append("<div class='option-overlay'>").append($("<div class='option-wrapper'>").append("<p>"+ questions[i].option1).append("<input type='hidden' id='"+viewId+"-"+questions[i].qid+"-1' name='score[]' value='"+questions[i].score1+"'/>"))).append($("<div class='option"+slidesCtrl+"'>").append("<div class='option-overlay'>").append($("<div class='option-wrapper'>").append("<p>"+ questions[i].option2).append("<input type='hidden' id='"+viewId+"-"+questions[i].qid+"-2' name='score[]' value='"+questions[i].score2+"'/>"))).appendTo("#view-"+(i)+"");$("#view-"+ i).append($("<div class='clear'>")).append($("<div class='slide-control'>").append(back).append("<button class='btn skip"+skip+"'>跳過這題"));};var height=1200;if($(window).width()<480)
height=3000;$("#questions").slidesjs({width:900,height:height,pagination:{active:false},navigation:{active:false},callback:{start:function(number){nStart=number;},complete:function(number){nStop=number;if(nStop>nStart)
$("#progress-bar").children().eq(number-1).addClass("current");}}});}).error(function(){alert("哎呀！出了些問題！將重新載入遊戲。");window.location.reload();});var startTime;$(document).ready(function(){var windowHeight=$(window).height();if($(".full-page").height()<windowHeight)
$(".full-page").height(windowHeight);$("#intro").show("slide",{direction:'right'}).find(".content").verti();$(".footer .logo").each(function(){$(this).css({"margin-top":($(this).parent().height()- $(this).height())/2});});$(".start").click(function(){startTime=new Date();});$(".show-next").click(function(event){event.preventDefault();$(this).parents(".full-page").hide(10).next().show('slide',{direction:'right'}).find(".content").verti();});$(document).on({click:function(){for(var i=0;i<$("#view-overlay").children().length;i++){var viewSelected=$("#view-overlay").children().eq(i).hasClass("selected");if(viewSelected)
$("#view-"+ i).prepend("<div class='weighted'><img src='img/weighted.png'>我關心的議題");}}},'#views .btn');$(document).on({click:function(){if($(this).hasClass("selected"))
$(this).removeClass("selected").stop(true);else{$('.candidate-selection a').removeClass("selected").stop(true);$(this).addClass("selected").effect("shake",{direction:"up",distance:5,times:10},6000);$("#candidates button").text("我選好了").removeClass("skip").addClass("next");}}},'#candidate-heads .candidate-selection a');$(document).on({mouseenter:function(){var index=$(this).index();$("#view-overlay").children().eq(index).animate({opacity:1},100);},mouseleave:function(){var index=$(this).index();var thisView=$("#view-overlay").children().eq(index);if(!thisView.hasClass("selected"))thisView.animate({opacity:0},100);},click:function(){var index=$(this).index();var thisView=$("#view-overlay").children().eq(index);if(thisView.hasClass("selected"))
thisView.animate({opacity:0},100).removeClass("selected").find("div").remove();else
thisView.addClass("selected").append("<div class='check'>");}},'.view');$(document).on({mouseenter:function(){$(this).find($(".option-overlay")).animate({opacity:1},100);},mouseleave:function(){var thisOption=$(this).find($(".option-overlay"));if(!thisOption.hasClass("selected"))
thisOption.animate({opacity:0},100);},click:function(){var thisOption=$(this).find(".option-overlay");var otherOption=$(this).siblings().find(".option-overlay");var thisInput=$(this).find("input");var otherInput=$(this).siblings().find("input");if(thisOption.hasClass("selected")){thisOption.animate({opacity:0},100).removeClass("selected").find(".check").remove();}else{thisOption.addClass("selected").append("<div class='check'>");thisInput.addClass("count");}
if(otherOption.hasClass("selected"))
otherOption.animate({opacity:0},100).removeClass("selected").find(".check").remove();if(otherInput.hasClass("count"))
otherInput.removeClass("count");}},".option");$(document).on({click:function(){$("#test").slideUp(400);$("#results").slideDown(200);$(".footer").show();getResult();},touchstart:function(){$("#test").slideUp(400);$("#results").slideDown(200);$(".footer").show();getResult();}},".last-question");$(document).on({click:function(){var isShare1=$(this).parent().hasClass("share-1");var option=(isShare1)?1:2;$.ajax({type:"POST",url:"saveShare.php",data:{share:"share",option:option}});}},".share button")});function getResult(){var endTime=new Date();var choosenCandi=$("#candidate-heads").find(".selected");if(choosenCandi.length==0)
choosenCandi=0
else{choosenCandi=choosenCandi.parent().attr("class").match(/\d+/)[0];var choosenName=candidates[choosenCandi-1].name;}
var choosen=[];var choosenView=[];var result=[0,0,0];var weightedCount=0;for(var i=0;i<$("#view-overlay").children().length;i++){var view=$("#view-overlay").children().eq(i);var weighted=view.hasClass("selected");var weight=1;if(weighted){weight=2;choosenView.push(view.attr("id").substr(2));weightedCount++;}
var selectedCount=$("#view-"+ i).find(".count");var choosenId=selectedCount.attr("id");choosen.push(choosenId);var selectedOption=selectedCount.parent();if(selectedCount.length==0){var score=[0,0,0];}else{var score=selectedCount.val().split(",");}
for(var j=0;j<score.length;j++){if(score[j]>0){var selectedQuestion=selectedOption.parents(".question");var selectedOptionTitle=selectedQuestion.find(".view-title");var selectedOptionIcon=selectedQuestion.find(".view-icon");$("<div class='view-result' >").append(selectedOptionIcon.clone()).append(selectedOptionTitle.clone()).append($("<div class='view-result-detail'>").append(selectedOption.clone())).appendTo("#view-check-"+(j+ 1)+" .list");};};result.add(score.multiply(weight));};if(weightedCount==9){result.devide(2);}
if($(window).width()>=480)
$(".sep-line").height(function(){return $(this).parent().height();}).css("margin-top","230px");else{for(var i=0;i<result.length;i++){if(result[i]==0)
$("#view-check-"+(i+1)).hide();};}
$.ajax({type:"POST",url:"saveResult.php",data:{save:"save",candi:choosenCandi,view:choosenView,choosen:choosen,start:startTime,end:endTime}});for(var i=0;i<result.length;i++){candidates[i].score=result[i];};candidates.sort(function(a,b){return b.score- a.score});var data={scores:[],colors:[],cid:[]};for(var i=0;i<candidates.length;i++){data.scores.push(candidates[i]["score"]);data.colors.push(candidates[i]["color"]);data.cid.push(candidates[i]["cid"]);};var viewLaugh=isLaugh(data.scores.slice(0));for(var i=0;i<viewLaugh.length;i++){var id=data.cid[i];if(viewLaugh[i]==1)
$("#view-check-"+ id+" .face").append("<img src='img/"+id+"-l.png'>");else{$("#view-check-"+ id+" .face").append("<img src='img/"+id+"-a.png'>");}};if(choosenCandi!=0)
$(".murmur").text("「"+ choosenName+"」原本是你想投的，但根據你選的政見，分析潛意識中你所愛的候選人比例，結果如下：");else
$(".murmur").text("原本你還沒想好要投給誰，但根據你選的政見，分析潛意識中你所愛的候選人比例，結果如下：");var canvas=document.getElementById("chart");var chart=canvas.getContext("2d");var drawDount=new drawdountChart(chart);drawDount.set(600,300,200,-Math.PI/2,Math.PI*3/2,70,"#727171",6);drawDount.draw(data);var dataURL=canvas.toDataURL();document.getElementById('chartImg').src=dataURL;var imgName=result.toString().replace(/,/g,"");$.ajax({type:"POST",url:"saveImg.php",data:{img:dataURL,name:imgName}});var url="http://www.facebook.com/sharer.php?u=http://test.thenewslens.com?r="+ imgName;$(".share-1").attr("href",url);var conWidth=$("#canvas-container").width();$("#chart").width(conWidth).height(conWidth/2);}
function drawdountChart(canvas){function drawHead(id,laugh){if(laugh==1){switch(id){case 1:return drawHead1Laugh(canvas);case 2:return drawHead2Laugh(canvas);case 3:return drawHead3Laugh(canvas);}}
switch(id){case 1:return drawHead1(canvas);case 2:return drawHead2(canvas);case 3:return drawHead3(canvas);}}
this.x,this.y,this.radius,this.lineWidth,this.strokeStyle,this.from,this.to=null;this.set=function(x,y,radius,from,to,lineWidth,strokeStyle,strokeWidth)
{this.x=x;this.y=y;this.radius=radius;this.from=from;this.to=to;this.lineWidth=lineWidth;this.strokeStyle=strokeStyle;this.strokeWidth=strokeWidth;}
this.draw=function(data)
{canvas.fillStyle="#f0f0f0";canvas.fillRect(0,0,1200,630);if(data.scores[0]==0&&data.scores[1]==0&&data.scores[2]==0){drawNull(canvas);}else{canvas.beginPath();canvas.lineWidth=this.lineWidth;canvas.strokeStyle="#bbbcbc";canvas.translate(this.x,this.y);canvas.arc(0,0,this.radius,this.from,this.to);canvas.stroke();canvas.strokeStyle=this.strokeStyle;var parts=percentage(data.scores);var laugh=isLaugh(data.scores);var size=resize(parts,.5,1);var fontSize=resize(parts,18,36);var numberOfParts=parts.length;var colors=data.colors;var df=-Math.PI/2;var arcCenterX=[];var arcCenterY=[];var id=data.cid;for(var i=0;i<numberOfParts;i++){canvas.beginPath();canvas.strokeStyle=colors[i];canvas.arc(0,0,this.radius,df,df+(Math.PI*2)*(parts[i]/100));canvas.lineWidth=(this.lineWidth- this.strokeWidth);canvas.stroke();df+=(Math.PI*2)*(parts[i]/100)/2;canvas.beginPath();arcCenterX.push(Math.cos(df)*this.radius);arcCenterY.push(Math.sin(df)*this.radius);canvas.arc(arcCenterX[i],arcCenterY[i],7,0,2*Math.PI);canvas.fillStyle="#727171";canvas.strokeStyle="#727171";canvas.fill();df+=(Math.PI*2)*(parts[i]/100)/2;}
var pos=[[400,0],[-350,125],[-350,-125]];var diff=Math.abs(pos[1][1]-arcCenterY[1]);if(pos[1][0]+ diff>arcCenterX[1]){var offset=pos[1][0]+ diff- arcCenterX[1];pos[1][0]-=offset;pos[2][0]-=offset;}
canvas.beginPath();canvas.moveTo(pos[0][0],pos[0][1]);diff=Math.abs(pos[0][1]-arcCenterY[0]);canvas.lineTo(pos[0][0]- diff,arcCenterY[0]);canvas.moveTo(pos[0][0]- diff,arcCenterY[0]);canvas.lineTo(arcCenterX[0],arcCenterY[0]);canvas.lineWidth="3";canvas.stroke();canvas.beginPath();canvas.moveTo(pos[1][0],pos[1][1]);diff=Math.abs(pos[1][1]-arcCenterY[1]);canvas.lineTo(pos[1][0]+ diff,arcCenterY[1]);canvas.moveTo(pos[1][0]+ diff,arcCenterY[1]);canvas.lineTo(arcCenterX[1],arcCenterY[1]);canvas.stroke();canvas.beginPath();canvas.moveTo(pos[2][0],pos[2][1]);diff=Math.abs(pos[2][1]-arcCenterY[2]);canvas.lineTo(pos[2][0]+ diff,arcCenterY[2]);canvas.moveTo(pos[2][0]+ diff,arcCenterY[2]);canvas.lineTo(arcCenterX[2],arcCenterY[2]);canvas.stroke();var headPos0=[pos[0][0]-200*size[0]/2,pos[0][1]-200*size[0]/2];var headPos1=[pos[1][0]-200*size[1]/2,pos[1][1]-200*size[1]/2];var headPos2=[pos[2][0]-200*size[2]/2,pos[2][1]-200*size[2]/2];canvas.translate(headPos0[0],headPos0[1]);canvas.scale(size[0],size[0]);drawHead(id[0],laugh[0]);canvas.scale(1/size[0],1/size[0]);canvas.translate(-headPos0[0],-headPos0[1]);canvas.translate(headPos1[0],headPos1[1]);canvas.scale(size[1],size[1]);drawHead(id[1],laugh[1]);canvas.scale(1/size[1],1/size[1]);canvas.translate(-headPos1[0],-headPos1[1]);canvas.translate(headPos2[0],headPos2[1]);canvas.scale(size[2],size[2]);drawHead(id[2],laugh[2]);canvas.scale(1/size[2],1/size[2]);canvas.translate(-headPos2[0],-headPos2[1]);canvas.font="600 "+fontSize[0]+"px Arial";canvas.textAlign="center";canvas.fillStyle="#727171";canvas.fillText(Math.round(parts[0])+"%",400,130);canvas.font="600 "+fontSize[1]+"px Arial";canvas.fillText(Math.round(parts[1])+"%",-350,155+200*size[1]/2);canvas.font="600 "+fontSize[2]+"px Arial";canvas.fillText(Math.round(parts[2])+"%",-350,-95+200*size[2]/2);}}}
if(!Array.prototype.repeat){Array.prototype.repeat=function(what,L){while(L)this[--L]=what;return this;};};if(!Array.prototype.add){Array.prototype.add=function(what){var i=0;while(i<what.length)this[i]=this[i]*1+ what[i++]*1;return this;};};if(!Array.prototype.shuffle){Array.prototype.shuffle=function(){var currentIndex=this.length,temporaryValue,randomIndex;while(0!==currentIndex){randomIndex=Math.floor(Math.random()*currentIndex);currentIndex-=1;temporaryValue=this[currentIndex];this[currentIndex]=this[randomIndex];this[randomIndex]=temporaryValue;}
return this;};};if(!Array.prototype.multiply){Array.prototype.multiply=function(what){for(var i=0;i<this.length;i++)this[i]*=what;return this;};};if(!Array.prototype.devide){Array.prototype.devide=function(what){for(var i=0;i<this.length;i++)this[i]/=what;return this;};};if(!Array.prototype.max){Array.prototype.max=function(){return Math.max.apply(null,this);};};function percentage(array){var count=0;for(var i=array.length- 1;i>=0;i--){count+=array[i];};for(var i=array.length- 1;i>=0;i--){array[i]=Math.round(array[i]/count*1000)/10;};return array;};if(!jQuery.fn.verti){jQuery.fn.verti=function(){if(this.height()<$(window).height()){this.css({'position':'relative','margin-top':($(window).height()- this.height())/2});}
return this;};};function currentTime(){var currentdate=new Date();return currentdate.getFullYear()+"-"
+(currentdate.getMonth()+1)+"-"
+ currentdate.getDate()+" "
+ currentdate.getHours()+":"
+ currentdate.getMinutes()+":"
+ currentdate.getSeconds();}
function resize(array,min,max){if(array[0]==array[2]){return[max,max,max];}else if(array[0]==array[1]){return[max,max,min];}else if(array[1]==array[2]){return[max,min,min];}else{var newArr=array.slice(0);newArr[0]=max;newArr[1]=interp(min,max,getK(array[1],array[2],array[0]));newArr[2]=min;return newArr;}}
function interp(min,max,k){return min+(max- min)*k;}
function getK(n,min,max){return(n-min)/(max-min);}
function isLaugh(array){if(array[0]==array[1]&&array[1]==array[2]){if(array[0]==0)
return[0,0,0];else
return[1,1,1];}
if(array[0]==array[1])
return[1,1,0];return[1,0,0];}